services:
  rpg_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: rpg_db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    restart: always

volumes:
  db: